services:
  wss-server:
    build:
      context: ./bin
      dockerfile: Dockerfile
    ports:
      - "3001:443"
    environment:
      - NODE_ENV=production
      - PORT=443
  config:
    build:
      context: ./server-config
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
  app:
    build:
      context: ./
      dockerfile: Dockerfile-app
    ports:
      - "5173:5173"