services:
  wss-server:
    build:
      context: ./bin
      dockerfile: Dockerfile
    ports:
      - "443:443"
    environment:
      - NODE_ENV=production
      - PORT=443
  config:
    build:
      context: ./server-config
      dockerfile: Dockerfile
    ports:
        - "3000:3000"