export class PresetManager {
    static presets = [
        {
            name: "Basic Kit",
            type: "Drumkit",
            isFactoryPresets: true,
            samples: [
                { url: "./audio/Basic Kit/kick.wav", name: "kick" },
                { url: "./audio/Basic Kit/snare.wav", name: "snare" },
                { url: "./audio/Basic Kit/hihat.wav", name: "hihat" },
                { url: "./audio/Basic Kit/tom1.wav", name: "tom1" },
                { url: "./audio/Basic Kit/tom2.wav", name: "tom2" },
                { url: "./audio/Basic Kit/tom3.wav", name: "tom3" },
            ],
        },
        {
            name: "Electronic",
            type: "Drumkit",
            isFactoryPresets: true,
            samples: [
                { url: "./audio/Electronic/kick.wav", name: "kick" },
                { url: "./audio/Electronic/snare.wav", name: "snare" },
                { url: "./audio/Electronic/tom1.wav", name: "tom1" },
                { url: "./audio/Electronic/tom2.wav", name: "tom2" },
                { url: "./audio/Electronic/tom3.wav", name: "tom3" },
                { url: "./audio/Electronic/tom4.wav", name: "tom4" },
                { url: "./audio/Electronic/hihat1.wav", name: "hihat1" },
                { url: "./audio/Electronic/hihat2.wav", name: "hihat2" },
                { url: "./audio/Electronic/clap1.wav", name: "clap1" },
                { url: "./audio/Electronic/clap2.wav", name: "clap2" },
                { url: "./audio/Electronic/crash1.wav", name: "crash1" },
                { url: "./audio/Electronic/crash2.wav", name: "crash2" },
                { url: "./audio/Electronic/ride1.wav", name: "ride1" },
                { url: "./audio/Electronic/ride2.wav", name: "ride2" },
                { url: "./audio/Electronic/perc1.wav", name: "perc1" },
                { url: "./audio/Electronic/perc2.wav", name: "perc2" },
            ],
        },
        {
            name: "808",
            type: "Drumkit",
            isFactoryPresets: true,
            samples: [
                { url: "./audio/808/Kick 808X.wav", name: "kick" },
                { url: "./audio/808/Snare 808 1.wav", name: "snare1" },
                { url: "./audio/808/Snare 808X.wav", name: "snare2" },
                { url: "./audio/808/HiTom 808.wav", name: "tom1" },
                { url: "./audio/808/MidTom 808.wav", name: "tom2" },
                { url: "./audio/808/LowTom 808.wav", name: "tom3" },
                { url: "./audio/808/ClosedHH 808.wav", name: "closed hihats"},
                { url: "./audio/808/OpenHH 808 1.wav", name: "open hihats1"},
                { url: "./audio/808/OpenHH 808 2.wav", name: "open hihats2"},
                { url: "./audio/808/Clap 808.wav", name: "clap1" },
                { url: "./audio/808/Clap 808X.wav", name: "clap2" },
                { url: "./audio/808/Rimshot 808.wav", name: "rimshot" },
                { url: "./audio/808/Cymbal 808X.wav", name: "cymbal" },
                { url: "./audio/808/Clave 808.wav", name: "clave" },
                { url: "./audio/808/Maracas 808.wav", name: "maracas" },
                { url: "./audio/808/Cowbell 808.wav", name: "cowbell" },
            ],
        },
        {
            name: "Hip-Hop",
            type: "Drumkit",
            isFactoryPresets: true,
            samples: [
                { url: "./audio/Hip Hop/Kick HipHop 1.wav", name: "kick1"},
                { url: "./audio/Hip Hop/Kick HipHop 2.wav", name: "kick2"},
                { url: "./audio/Hip Hop/Snare HipHop 1.wav", name: "snare1"},
                { url: "./audio/Hip Hop/Snare HipHop 2.wav", name: "snare2"},
                { url: "./audio/Hip Hop/ClosedHH HipHop 1.wav", name: "closed hihats1"},
                { url: "./audio/Hip Hop/ClosedHH HipHop 2.wav", name: "closed hihats2"},
                { url: "./audio/Hip Hop/Clap HipHop.wav", name: "clap"},
                { url: "./audio/Hip Hop/Crash HipHop.wav", name: "crash"},
                { url: "./audio/Hip Hop/RevCymbal HipHop.wav", name: "reverse cymbal"},
                { url: "./audio/Hip Hop/Ride HipHop.wav", name: "ride"},
                { url: "./audio/Hip Hop/Triangle HipHop.wav", name: "triangle"},
                { url: "./audio/Hip Hop/Vibraslap HipHop.wav", name: "vibraslap"},
                { url: "./audio/Hip Hop/Wood HipHop.wav", name: "wood"},
                { url: "./audio/Hip Hop/Clave HipHop.wav", name: "clave"},
                { url: "./audio/Hip Hop/Combo HipHop 1.wav", name: "combo1"},
                { url: "./audio/Hip Hop/Combo HipHop 2.wav", name: "combo2"},
            ],
        },
        {
            name: "Garage",
            type: "Drumkit",
            isFactoryPresets: true,
            samples: [
                { url: "./audio/Garage/Kick Garage.wav", name: "kick"},
                { url: "./audio/Garage/Snare Garage.wav", name: "snare"},
                { url: "./audio/Garage/ClosedHH Garage.wav", name: "closed hihats"},
                { url: "./audio/Garage/OpenHH Garage.wav", name: "open hihats"},
                { url: "./audio/Garage/PedalHH Garage.wav", name: "pedal hihats"},
                { url: "./audio/Garage/HiTom Garage.wav", name: "tom1"},
                { url: "./audio/Garage/MidTom Garage.wav", name: "tom2"},
                { url: "./audio/Garage/LowTom Garage.wav", name: "tom3"},
                { url: "./audio/Garage/Clap Garage.wav", name: "clap"},
                { url: "./audio/Garage/SnareRim Garage.wav", name: "rimshot"},
                { url: "./audio/Garage/Crash Garage.wav", name: "crash"},
                { url: "./audio/Garage/Ride Garage.wav", name: "ride"},
                { url: "./audio/Garage/Splash Garage.wav", name: "splash"},
                { url: "./audio/Garage/Cowbell Garage.wav", name: "cowbell"},
                { url: "./audio/Garage/StickHit Garage.wav", name: "stick hit"},
                { url: "./audio/Garage/TambTap Garage.wav", name: "tambourine"},

            ],
        },
        {
            name: "Funky",
            type: "Drumkit",
            isFactoryPresets: true,
            samples: [
                { url: "./audio/Funky/Kick Funk 1.wav", name: "kick"},
                { url: "./audio/Funky/Snare Funk 1.wav", name: "snare"},
                { url: "./audio/Funky/ClosedHH Funk 1.wav", name: "closed hihats"},
                { url: "./audio/Funky/OpenHH Funk 1.wav", name: "open hihats"},
                { url: "./audio/Funky/Clap Funk 1.wav", name: "clap"},
                { url: "./audio/Funky/Rimshot Funk 1.wav", name: "rimshot"},
                { url: "./audio/Funky/Perc Funk 1.wav", name: "perc1"},
                { url: "./audio/Funky/Perc Funk 2.wav", name: "perc2"},
                { url: "./audio/Funky/Shaker Funk 1.wav", name: "shaker"},
                { url: "./audio/Funky/Bass Funk 3.wav", name: "bass1"},
                { url: "./audio/Funky/Chord Funk 1.wav", name: "chord1"},
                { url: "./audio/Funky/Chord Funk 2.wav", name: "chord2"},
                { url: "./audio/Funky/Pad Funk.wav", name: "pad"},
                { url: "./audio/Funky/Vox Funk.wav", name: "vox"},
            ],
        },
        {
            name: "House",
            type: "Drumkit",
            isFactoryPresets: true,
            samples: [
                { url: "./audio/House/Kick House 1.wav", name: "kick1"},
                { url: "./audio/House/Kick House 2.wav", name: "kick2"},
                { url: "./audio/House/Snare House 1.wav", name: "snare"},
                { url: "./audio/House/ClosedHH House 1.wav", name: "closed hihats"},
                { url: "./audio/House/OpenHH House 1.wav", name: "open hihats"},
                { url: "./audio/House/Clap House 1.wav", name: "clap"},
                { url: "./audio/House/Cymbal House.wav", name: "cymbal"},
                { url: "./audio/House/Shaker House 1.wav", name: "shaker"},
                { url: "./audio/House/Bass House 1.wav", name: "bass1"},
                { url: "./audio/House/Bass House 2.wav", name: "bass2"},
                { url: "./audio/House/Bass House 3.wav", name: "bass3"},
                { url: "./audio/House/Piano House 1.wav", name: "piano1"},
                { url: "./audio/House/Piano House 2.wav", name: "piano2"},
                { url: "./audio/House/Organ House 1.wav", name: "organ1"},
                { url: "./audio/House/Organ House 2.wav", name: "organ2"},
                { url: "./audio/House/Organ House 3.wav", name: "organ3"},
            ],
        },
        {
            name: "Pop",
            type: "Drumkit",
            isFactoryPresets: true,
            samples: [
                { url: "./audio/Pop/Kick Alphabetical 1.wav", name: "kick"},
                { url: "./audio/Pop/Snare Alphabetical 1.wav", name: "snare"},
                { url: "./audio/Pop/ClosedHH Alphabetical 1.wav", name: "closed hihats"},
                { url: "./audio/Pop/OpenHH Alphabetical.wav", name: "open hihats"},
                { url: "./audio/Pop/Clap Alphabetical 1.wav", name: "clap"},
                { url: "./audio/Pop/Perc Alphabetical 1.wav", name: "perc1"},
                { url: "./audio/Pop/Perc Alphabetical 2.wav", name: "perc2"},
                { url: "./audio/Pop/Shaker Alphabetical 1.wav", name: "shaker"},
                { url: "./audio/Pop/Bass Alphabetical 1.wav", name: "bass1"},
                { url: "./audio/Pop/Bass Alphabetical 2.wav", name: "bass2"},
                { url: "./audio/Pop/Bass Alphabetical 3.wav", name: "bass3"},
                { url: "./audio/Pop/Synth Alphabetical 1.wav", name: "synth1"},
                { url: "./audio/Pop/Synth Alphabetical 2.wav", name: "synth2"},
                { url: "./audio/Pop/Synth Alphabetical 3.wav", name: "synth3"},
                { url: "./audio/Pop/Vox Alphabetical 1.wav", name: "vox1"},
                { url: "./audio/Pop/Vox Alphabetical 2.wav", name: "vox2"},
            ],
        },
        {
            name: "Steveland Vinyl",
            type: "Drumkit",
            isFactoryPresets: true,
            samples: [
                { url: "./audio/Steveland Vinyl/Kick Steveland 1.wav", name: "kick"},
                { url: "./audio/Steveland Vinyl/Snare Steveland 1.wav", name: "snare1"},
                { url: "./audio/Steveland Vinyl/Snare Steveland 2.wav", name: "snare2"},
                { url: "./audio/Steveland Vinyl/ClosedHH Steveland.wav", name: "closed hihats"},
                { url: "./audio/Steveland Vinyl/OpenHH Steveland.wav", name: "open hihats"},
                { url: "./audio/Steveland Vinyl/Tom Steveland 1.wav", name: "tom1"},
                { url: "./audio/Steveland Vinyl/Tom Steveland 2.wav", name: "tom2"},
                { url: "./audio/Steveland Vinyl/Tom Steveland 3.wav", name: "tom3"},
                { url: "./audio/Steveland Vinyl/Tom Steveland 4.wav", name: "tom4"},
                { url: "./audio/Steveland Vinyl/Conga Steveland 1.wav", name: "conga"},
                { url: "./audio/Steveland Vinyl/Bass Steveland 1.wav", name: "bass1"},
                { url: "./audio/Steveland Vinyl/Bass Steveland 2.wav", name: "bass2"},
                { url: "./audio/Steveland Vinyl/Rhodes Steveland 1.wav", name: "rhodes"},
                { url: "./audio/Steveland Vinyl/Scratch Steveland 1.wav", name: "scratch1"},
                { url: "./audio/Steveland Vinyl/Scratch Steveland 2.wav", name: "scratch2"},
                { url: "./audio/Steveland Vinyl/Scratch Steveland 3.wav", name: "scratch3"},
            ],
        },
        {
            name: "Grand Piano",
            type: "Orchestra",
            isFactoryPresets: true,
            samples: [
                { url: "./audio/Grand Piano/piano-f-a4.wav", name: "piano A4"},
                { url: "./audio/Grand Piano/piano-f-a5.wav", name: "piano A5"},
                { url: "./audio/Grand Piano/piano-f-a6.wav", name: "piano A6"},
                { url: "./audio/Grand Piano/piano-f-c4.wav", name: "piano C4"},
                { url: "./audio/Grand Piano/piano-f-c5.wav", name: "piano C5"},
                { url: "./audio/Grand Piano/piano-f-c6.wav", name: "piano C6"},
                { url: "./audio/Grand Piano/piano-f-ds4.wav", name: "piano D#4"},
                { url: "./audio/Grand Piano/piano-f-ds5.wav", name: "piano D#5"},
                { url: "./audio/Grand Piano/piano-f-ds6.wav", name: "piano D#6"},
                { url: "./audio/Grand Piano/piano-f-fs4.wav", name: "piano F#4"},
                { url: "./audio/Grand Piano/piano-f-fs5.wav", name: "piano F#5"},
                { url: "./audio/Grand Piano/piano-f-fs6.wav", name: "piano F#6"},
            ],
        }
    ];
    
}